#pragma once

// VDK.h is autogenerated from VisualDSP into your project folder
#include <VDK.h>

#ifndef _ADI_THREADS
#error Is VDK active and -thread option specified?
#endif

namespace estd { 
    
namespace thread {

typedef VDK::ThreadID id;

class thread
{
public:
    template <class Function, class TParam1>
    thread(Function f, TParam1 param)
    {
        
    }
};

}

namespace this_thread {

inline estd::thread::id get_id()
{
    return VDK::GetThreadID();
}

}

}